version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-catalog
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
